"""documento_int

Revision ID: 9c64a21c6911
Revises: 
Create Date: 2026-06-18 23:32:48.061175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c64a21c6911'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('documento', sa.BigInteger(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('numero', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estoque',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.Column('tipo_funcionario', sa.Enum('ADMIN', 'GERENTE', 'ATENDENTE', 'COZINHA', name='tipofuncionario'), nullable=False),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_unidade', sa.Integer(), nullable=True),
    sa.Column('id_funcionario', sa.Integer(), nullable=True),
    sa.Column('canal_pedido', sa.Enum('APP', 'TOTEM', 'BALCAO', 'WEB', name='canalpedido'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PAGO', 'PREPARACAO', 'PRONTO', 'CANCELADO', name='statuspedido'), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['id_funcionario'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['id_unidade'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_produto', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('preco_unitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PAGO', 'RECUSADO', name='statuspagamento'), nullable=False),
    sa.Column('data_transacao', sa.Date(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=True),
    sa.Column('metodo_pagamento', sa.Enum('PIX', 'DEBITO', 'CREDITO', 'DINHEIRO', name='metodopagamento'), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    op.drop_table('funcionarios')
    op.drop_table('estoque')
    op.drop_table('unidades')
    op.drop_table('produtos')
    op.drop_table('clientes')
    # ### end Alembic commands ###
